# Generated by Django 4.2.6 on 2023-11-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_final_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('legal_adress', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company'),
        ),
    ]
