# Generated by Django 4.2.6 on 2023-11-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_company_alter_user_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
