# Generated by Django 4.2.6 on 2023-11-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='adress',
            new_name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='access',
            field=models.CharField(blank=True, choices=[('открыт', 'Открыт'), ('закрыт', 'Закрыт')], default='закрыт', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
