# Generated by Django 4.2.6 on 2024-02-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_direction_user_direction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(blank=True, choices=[('базовым', 'Basic'), ('разрешенным', 'Pro')], default='базовым', max_length=20, null=True),
        ),
    ]
