# Generated by Django 4.2.6 on 2024-03-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan',
            field=models.CharField(blank=True, choices=[('базовый', 'Basic'), ('расширенный', 'Pro')], default='базовый', max_length=20, null=True),
        ),
    ]
