# Generated by Django 4.2.6 on 2024-03-25 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'в очереди'), (1, 'доставлено'), (2, 'не доставлено'), (3, 'передано'), (4, 'ожидание статуса сообщения'), (6, 'сообщение отклонено'), (8, 'на модерации')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
