version: "3.9"

services:
  db:
    image: postgres:15
    container_name: remote_postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./myproject/.env

  remote_project:
    build:
      dockerfile: Dockerfile
      context: .
    image: remote_test:latest
    container_name: remote_project
    depends_on:
      - db
    volumes:
      - static_volume:/remote/static
      - media_volume:/remote/media
    env_file:
      - ./myproject/.env
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py migrate  && gunicorn -b 0.0.0.0:8000 myproject.wsgi:application"
    ports:
      - 8000:8000

  # nginx:
  #   build:
  #     dockerfile: ./Dockerfile
  #     context: ./docker/nginx/
  #   container_name: remote_nginx
  #   volumes:
  #     - static_volume:/remote/static
  #     - media_volume:/remote/media
  #   depends_on:
  #     - remote_project
  #   ports:
  #     - "${EXTERNAL_PORT}:80"

volumes:
  static_volume: 
  media_volume:


