version: '3.8'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 myproject.wsgi:application
    volumes:
      - .:/app
    ports:
      - 8000:8000
  
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  celery-beat:
      build: .
      command: celery -A myproject beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler -S django
      environment:
          - DEBUG=1
          - CELERY_BROKER=redis://redis:6379/0
          - CELERY_BACKEND=redis://redis:6379/0
      volumes:
          - .:/app
      depends_on:
      - redis
      - web
  celery-worker:
      build: .
      command: celery -A myproject worker -l INFO
      environment:
          - DEBUG=1
          - CELERY_BROKER=redis://redis:6379/0
          - CELERY_BACKEND=redis://redis:6379/0
      volumes:
          - .:/app
      depends_on:
      - redis
      - web

  redis:
    image: redis:7.2