# Generated by Django 4.1.7 on 2023-10-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_answer_question_id_alter_statistic_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
