# Generated by Django 4.1.7 on 2023-10-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_statistic_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
