# Generated by Django 4.1.7 on 2023-10-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='question_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='my_app.question'),
        ),
    ]
