# Generated by Django 4.2.6 on 2023-11-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_question_note_question_question_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
