# Generated by Django 4.1.7 on 2023-10-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_statistic_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='category',
            field=models.CharField(choices=[('BILMIREM', 'Bilmirem'), ('BILIREM', 'Bilirem'), ('TAMBILIREM', 'Tambilirem'), ('ORGENIREM', 'Orgenirem')], default='BILIREM', max_length=50),
        ),
    ]
