# Generated by Django 4.1.7 on 2023-10-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_statistic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='category',
            field=models.CharField(choices=[('EDEMMIREM', 'Edemirem'), ('BILMIREM', 'Bilmirem'), ('SEHVLEREDIREM', 'Sehvleredirem'), ('TAMBILIREM', 'Tambilirem')], default='EDEMMIREM', max_length=50),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='correct_answers',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='incorrect_answers',
            field=models.FloatField(),
        ),
    ]
