# Generated by Django 4.1.7 on 2023-10-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_statistic_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='correct_answers',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='incorrect_answers',
            field=models.FloatField(default=0),
        ),
    ]
