# Generated by Django 4.2.6 on 2024-01-20 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_direction_user_direction_type'),
        ('my_app', '0006_alter_question_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='direction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.direction'),
        ),
    ]
