# Generated by Django 4.2.6 on 2023-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_statistic_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='category',
            field=models.CharField(choices=[('Не знаю', 'Bilmirem'), ('Делаю ошибки', 'Sehvleredirem'), ('Знаю', 'Tambilirem')], default='Не знаю', max_length=50),
        ),
    ]
