# Generated by Django 4.2.6 on 2024-03-24 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0008_alter_statistic_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalyTestQuestionForPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalytestquestion', to='my_app.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalytestquestion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
